name       : libkomparediff2
version    : 22.04.3
release    : 63
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.3/src/libkomparediff2-22.04.3.tar.xz : 13f11a4025c06ac685348fed5aa56f9ab967b3ef748942069cfa64c34e5f5ded
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
