name       : libkomparediff2
version    : 20.08.1
release    : 41
source     :
    - https://cdn.download.kde.org/stable/release-service/20.08.1/src/libkomparediff2-20.08.1.tar.xz : 9d109dfea1433602cdabc89ffa5f522147befc9b1d6d9760549aba7db5dbd399
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
    - kio-devel
    - kwindowsystem-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
