name       : libkomparediff2
version    : 22.04.2
release    : 62
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.2/src/libkomparediff2-22.04.2.tar.xz : a7713b5a7e32e7ed51f3b93668d6338b4674feb149d5d9514e3a9b53367fe609
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
