name       : libkomparediff2
version    : 18.04.3
release    : 13
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.3/src/libkomparediff2-18.04.3.tar.xz : e11a05cd551050a3a0ab423a9c05df420e2715fa33ab2450eecef2eda56249cf
license    :
    - BSD-3-Clause
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
