name       : libkomparediff2
version    : 22.04.1
release    : 61
source     :
    - https://cdn.download.kde.org/stable/release-service/22.04.1/src/libkomparediff2-22.04.1.tar.xz : e404db3115a2a669edd3010dcfd2b45b140481c8b98be9df08fae11d8a0ce33f
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
