name       : libkomparediff2
version    : 19.12.0
release    : 31
source     :
    - https://cdn.download.kde.org/stable/release-service/19.12.0/src/libkomparediff2-19.12.0.tar.xz : 39335b1b31dcac243df5543d4eaa5e230a262e23cd045c9e645e05079672001e
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
