name       : libkomparediff2
version    : 21.04.1
release    : 50
source     :
    - https://cdn.download.kde.org/stable/release-service/21.04.1/src/libkomparediff2-21.04.1.tar.xz : eced4e239b40278dcfff529db6f433c997c80da0c77faadf6a9b7c39d26ebdfe
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
