name       : libkomparediff2
version    : 23.04.0
release    : 66
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.0/src/libkomparediff2-23.04.0.tar.xz : 305a54f663203f549bc5a3c0903a3cc5353b459a9278a39d26c4566268812115
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
