name       : libkomparediff2
version    : 21.08.3
release    : 56
source     :
    - https://cdn.download.kde.org/stable/release-service/21.08.3/src/libkomparediff2-21.08.3.tar.xz : 1e47cd1cc462d62477eaec0dc26c266ee4b73ba38fb8ee279e85bd1827406928
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
