name       : libkomparediff2
version    : 18.08.0
release    : 14
source     :
    - https://cdn.download.kde.org/stable/applications/18.08.0/src/libkomparediff2-18.08.0.tar.xz : 47e88f40f3f6feaf7f6ad08de518c39d6ac1e013974411c0cedfd88d5230a65b
license    :
    - BSD-3-Clause
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
