name       : libkomparediff2
version    : 23.04.2
release    : 68
source     :
    - https://cdn.download.kde.org/stable/release-service/23.04.2/src/libkomparediff2-23.04.2.tar.xz : 958595c10e95ec19cf3451604f871edef69912f2496e1ac2870c2d871cd8a990
homepage   : https://kde.org/
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
optimize   : lto
builddeps  :
    - kio-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
