name       : libkomparediff2
version    : 19.08.3
release    : 30
source     :
    - https://cdn.download.kde.org/stable/applications/19.08.3/src/libkomparediff2-19.08.3.tar.xz : a1ba5616fda806d5aedab3fb080bbcef5e13c04153fd9659d9d47f0a1a11125d
license    :
    - GPL-2.0-or-later
    - LGPL-2.0-or-later
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake_ninja -DBUILD_TESTING=OFF
build      : |
    %ninja_build
install    : |
    %ninja_install
