name       : libkomparediff2
version    : 17.08.2
release    : 4
source     :
    - https://download.kde.org/stable/applications/17.08.2/src/libkomparediff2-17.08.2.tar.xz : 00690ec08490cac26e5d1899041b961eb5980dc5b15970b2b6b09d2da0078075
license    :
    - BSD-3-Clause
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %cmake .
build      : |
    %make
install    : |
    %make_install
