name       : libkomparediff2
version    : 18.04.2
release    : 12
source     :
    - https://cdn.download.kde.org/stable/applications/18.04.2/src/libkomparediff2-18.04.2.tar.xz : 87808eb8218b8a63ae9e7dd2d80f50de0f01b2cfae4e4acda66fdff86b217954
license    :
    - BSD-3-Clause
    - GPL-2.0
    - GPL-3.0
    - LGPL-2.0
    - LGPL-2.1
    - LGPL-3.0
component  : programming
optimize   : lto
summary    : Library to compare files and strings
description: |
    Library to compare files and strings, used in Kompare and KDevelop.
builddeps  :
    - pkgconfig(gl)
    - pkgconfig(Qt5Core)
    - extra-cmake-modules
    - kcodecs-devel
    - kconfig-devel
    - kcoreaddons-devel
    - ki18n-devel
    - kio-devel
    - kxmlgui-devel
setup      : |
    %patch -p1 < $pkgfiles/0001-Disable-building-unshipped-code.patch
    %cmake_ninja
build      : |
    %ninja_build
install    : |
    %ninja_install
